#!/usr/bin/env python3
from pathlib import Path
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else '.').resolve()

def read(rel):
    return (root / rel).read_text(encoding='utf-8')

def write(rel, text):
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding='utf-8')

def replace_exact(rel, old, new, count=1):
    text = read(rel)
    actual = text.count(old)
    if actual != count:
        raise SystemExit(f'REPLACE COUNT MISMATCH {rel}: expected {count}, found {actual}: {old[:120]!r}')
    write(rel, text.replace(old, new, count))

rel = 'app/src/main/java/com/tiagocrispo/furnitureshot/processing/DirectMediaPipeBackgroundGenerator.kt'
replace_exact(rel, 'import kotlinx.coroutines.CancellationException\n', 'import kotlinx.coroutines.CancellationException\nimport kotlinx.coroutines.ensureActive\nimport kotlin.coroutines.coroutineContext\n')
replace_exact(rel, '    fun tryGenerate(\n', '    suspend fun tryGenerate(\n')
replace_exact(rel, '            for (attempt in 0 until attemptCount) {\n                val prompt = promptVariants[attempt % promptVariants.size]\n', '            for (attempt in 0 until attemptCount) {\n                coroutineContext.ensureActive()\n                val prompt = promptVariants[attempt % promptVariants.size]\n')
replace_exact(rel, '                val result = generator.generate(prompt, iterations, seed)\n                val mpImage = result?.generatedImage() ?: continue\n', '                val result = generator.generate(prompt, iterations, seed)\n                coroutineContext.ensureActive()\n                val mpImage = result?.generatedImage() ?: continue\n')
replace_exact(rel, '            val dir = File(context.cacheDir, "productshot/direct-mediapipe").apply { mkdirs() }\n', '            coroutineContext.ensureActive()\n            val dir = File(context.cacheDir, "productshot/direct-mediapipe").apply { mkdirs() }\n')

rel = 'app/src/main/java/com/tiagocrispo/furnitureshot/processing/MediaPipeReflectiveBackgroundProvider.kt'
replace_exact(rel, '    fun tryRender(\n', '    suspend fun tryRender(\n')

rel = 'app/src/main/java/com/tiagocrispo/furnitureshot/processing/BackgroundGenerationBroker.kt'
replace_exact(rel, 'import android.content.Context\n', 'import android.content.Context\nimport kotlinx.coroutines.delay\nimport kotlinx.coroutines.ensureActive\nimport kotlin.coroutines.coroutineContext\n')
replace_exact(rel, '    fun tryAcquirePlate(\n', '    suspend fun tryAcquirePlate(\n')
replace_exact(rel, '        repeat(8) {\n            Thread.sleep(125)\n', '        repeat(8) {\n            coroutineContext.ensureActive()\n            delay(125)\n')

rel = 'app/src/main/java/com/tiagocrispo/furnitureshot/processing/LocalEnhancementEngine.kt'
replace_exact(rel, '        var output: Bitmap? = null\n        var plate: Bitmap? = null\n', '        var output: Bitmap? = null\n        var plate: Bitmap? = null\n        var transientBackgroundPath: String? = null\n')
replace_exact(rel, '            val backgroundPlan = BackgroundEngineCoordinator.resolve(\n', '            val backgroundPlan = BackgroundEngineCoordinator.resolve(\n')
replace_exact(rel, '            coroutineContext.ensureActive()\n            var studioStyle = backgroundPlan.style\n', '            transientBackgroundPath = backgroundPlan.backgroundPlatePath\n            coroutineContext.ensureActive()\n            var studioStyle = backgroundPlan.style\n', count=1)
replace_exact(rel, '            backgroundPlan.backgroundPlatePath?.let { ImageStore.deleteTransientCacheFile(context, it) }\n            coroutineContext.ensureActive()\n', '            coroutineContext.ensureActive()\n')
replace_exact(rel, '            val resultFile = saveJpeg(originalPath, output)\n            onProgress(100, "Listo")\n            return ProcessResult(\n', '            val resultFile = saveJpeg(originalPath, output)\n            // No cancellable callback after persistence: the UI owns the commit and\n            // can remove this file if cancellation wins the return race.\n            return ProcessResult(\n')
replace_exact(rel, '        } finally {\n            output?.let { if (!it.isRecycled) it.recycle() }\n', '        } finally {\n            ImageStore.deleteTransientCacheFile(context, transientBackgroundPath)\n            output?.let { if (!it.isRecycled) it.recycle() }\n', count=1)
replace_exact(rel, '    ): ProcessResult {\n        val file = withContext(Dispatchers.IO) { saveJpeg(originalPath, source) }\n', '    ): ProcessResult {\n        coroutineContext.ensureActive()\n        val file = withContext(Dispatchers.IO) { saveJpeg(originalPath, source) }\n')

rel = 'app/src/main/java/com/tiagocrispo/furnitureshot/data/ImageStore.kt'
old = '''    fun importUri(context: Context, uri: Uri): File {\n        val jobDir = File(context.filesDir, "$JOBS_DIR/${UUID.randomUUID()}").apply { mkdirs() }\n        val destination = File(jobDir, "original.jpg")\n        context.contentResolver.openInputStream(uri).use { input ->\n            requireNotNull(input) { "No se pudo abrir la imagen seleccionada." }\n            FileOutputStream(destination).use { output -> input.copyTo(output, 128 * 1024) }\n        }\n        return destination\n    }\n\n    fun importCameraFile(context: Context, cameraFile: File): File {\n        val jobDir = File(context.filesDir, "$JOBS_DIR/${UUID.randomUUID()}").apply { mkdirs() }\n        val destination = File(jobDir, "original.jpg")\n        cameraFile.inputStream().use { input ->\n            destination.outputStream().use { output -> input.copyTo(output, 128 * 1024) }\n        }\n        cameraFile.delete()\n        return destination\n    }\n'''
new = '''    fun importUri(context: Context, uri: Uri): File {\n        val jobDir = File(context.filesDir, "$JOBS_DIR/${UUID.randomUUID()}").apply { mkdirs() }\n        val destination = File(jobDir, "original.jpg")\n        val temp = File(jobDir, ".original.tmp")\n        return try {\n            context.contentResolver.openInputStream(uri).use { input ->\n                requireNotNull(input) { "No se pudo abrir la imagen seleccionada." }\n                FileOutputStream(temp).use { output ->\n                    input.copyTo(output, 128 * 1024)\n                    output.flush()\n                    output.fd.sync()\n                }\n            }\n            validateImageFile(temp, minimumBytes = 1_024L, minimumDimension = 64)\n            moveAtomically(temp, destination)\n            destination\n        } catch (t: Throwable) {\n            jobDir.deleteRecursively()\n            throw t\n        } finally {\n            if (temp.exists()) temp.delete()\n        }\n    }\n\n    fun importCameraFile(context: Context, cameraFile: File): File {\n        val jobDir = File(context.filesDir, "$JOBS_DIR/${UUID.randomUUID()}").apply { mkdirs() }\n        val destination = File(jobDir, "original.jpg")\n        val temp = File(jobDir, ".original.tmp")\n        return try {\n            cameraFile.inputStream().use { input ->\n                FileOutputStream(temp).use { output ->\n                    input.copyTo(output, 128 * 1024)\n                    output.flush()\n                    output.fd.sync()\n                }\n            }\n            validateImageFile(temp, minimumBytes = 1_024L, minimumDimension = 64)\n            moveAtomically(temp, destination)\n            destination\n        } catch (t: Throwable) {\n            jobDir.deleteRecursively()\n            throw t\n        } finally {\n            if (temp.exists()) temp.delete()\n            cameraFile.delete()\n        }\n    }\n'''
replace_exact(rel, old, new)
replace_exact(rel, '''            check(result.exists() && result.length() >= 8_192L) {\n                "El archivo final no superó la validación de integridad."\n            }\n            val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }\n            BitmapFactory.decodeFile(result.absolutePath, bounds)\n            check(bounds.outWidth >= 64 && bounds.outHeight >= 64) {\n                "El archivo final no se puede decodificar correctamente."\n            }\n            return result\n''', '''            validateImageFile(result, minimumBytes = 8_192L, minimumDimension = 64)\n            return result\n''')
insert_after = '''    private fun moveAtomically(source: File, destination: File) {\n        try {\n            Files.move(\n                source.toPath(),\n                destination.toPath(),\n                StandardCopyOption.ATOMIC_MOVE,\n            )\n        } catch (_: AtomicMoveNotSupportedException) {\n            Files.move(source.toPath(), destination.toPath())\n        }\n    }\n'''
addition = insert_after + '''\n    private fun validateImageFile(file: File, minimumBytes: Long, minimumDimension: Int) {\n        check(file.isFile && file.length() >= minimumBytes) {\n            "El archivo de imagen no superó la validación de integridad."\n        }\n        val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }\n        BitmapFactory.decodeFile(file.absolutePath, bounds)\n        check(bounds.outWidth >= minimumDimension && bounds.outHeight >= minimumDimension) {\n            "El archivo de imagen no se puede decodificar correctamente."\n        }\n    }\n\n    fun requireValidGeneratedResult(context: Context, resultPath: String): File {\n        val result = File(resultPath)\n        val jobsRoot = File(context.filesDir, JOBS_DIR)\n        val safe = runCatching {\n            result.canonicalFile.parentFile?.canonicalPath?.startsWith(jobsRoot.canonicalPath + File.separator) == true &&\n                GenerationArtifactPolicy.isGeneratedResultFileName(result.name)\n        }.getOrDefault(false)\n        require(safe) { "El resultado no pertenece a un trabajo válido." }\n        validateImageFile(result, minimumBytes = 8_192L, minimumDimension = 64)\n        return result\n    }\n'''
replace_exact(rel, insert_after, addition)
marker = '''    fun deleteGeneratedResult(context: Context, resultPath: String?) {\n        val result = resultPath?.let(::File) ?: return\n        val jobsRoot = File(context.filesDir, JOBS_DIR)\n        val safe = runCatching {\n            result.canonicalPath.startsWith(jobsRoot.canonicalPath + File.separator) &&\n                result.name.startsWith("result_") && result.extension == "jpg"\n        }.getOrDefault(false)\n        if (safe) result.delete()\n    }\n'''
addition2 = marker + '''\n    fun deleteUncommittedGeneratedResults(context: Context, originalPath: String, keepResultPath: String?) {\n        val original = File(originalPath)\n        val jobDir = original.parentFile ?: return\n        val jobsRoot = File(context.filesDir, JOBS_DIR)\n        val safeJob = runCatching {\n            jobDir.canonicalFile.parentFile?.canonicalPath == jobsRoot.canonicalPath\n        }.getOrDefault(false)\n        if (!safeJob) return\n\n        val protected = buildSet {\n            keepResultPath?.let(::add)\n            loadHistory(context).forEach { add(it.resultPath) }\n        }\n        val candidates = jobDir.listFiles()?.filter(File::isFile)?.map(File::getAbsolutePath).orEmpty()\n        GenerationArtifactPolicy.selectUncommitted(\n            jobDirectory = jobDir.absolutePath,\n            candidatePaths = candidates,\n            protectedPaths = protected,\n        ).forEach { File(it).delete() }\n    }\n'''
replace_exact(rel, marker, addition2)

rel = 'app/src/main/java/com/tiagocrispo/furnitureshot/ui/FurnitureShotApp.kt'
replace_exact(rel, '''                generatedPath = result.resultPath\n                coroutineContext.ensureActive()\n                stage = "Acabado final"\n                val finished = withContext(Dispatchers.IO) { FinishPassEngine.apply(result.resultPath) }\n                generatedPath = finished\n                coroutineContext.ensureActive()\n''', '''                generatedPath = result.resultPath\n                withContext(Dispatchers.IO) { ImageStore.requireValidGeneratedResult(context, result.resultPath) }\n                coroutineContext.ensureActive()\n                stage = "Acabado final"\n                val finished = withContext(Dispatchers.IO) { FinishPassEngine.apply(result.resultPath) }\n                generatedPath = finished\n                withContext(Dispatchers.IO) { ImageStore.requireValidGeneratedResult(context, finished) }\n                coroutineContext.ensureActive()\n''')
replace_exact(rel, '''            } finally {\n                if (!committed && generatedPath != null && generatedPath != previousResult) {\n                    withContext(NonCancellable + Dispatchers.IO) {\n                        ImageStore.deleteGeneratedResult(context, generatedPath)\n                    }\n                }\n                processing = false\n''', '''            } finally {\n                if (!committed) {\n                    withContext(NonCancellable + Dispatchers.IO) {\n                        // Scan the whole job, not only generatedPath: this also catches\n                        // the tiny cancellation race where persistence succeeds but the\n                        // suspended pipeline never returns its path to the UI.\n                        ImageStore.deleteUncommittedGeneratedResults(context, source, previousResult)\n                    }\n                }\n                processing = false\n''')

rel = 'app/src/main/java/com/tiagocrispo/furnitureshot/processing/FinishPassEngine.kt'
replace_exact(rel, '''    fun apply(resultPath: String): String {\n        val file = File(resultPath)\n        return if (file.exists()) file.absolutePath else resultPath\n    }\n''', '''    fun apply(resultPath: String): String {\n        val file = File(resultPath)\n        require(file.isFile) { "El resultado desapareció antes del acabado final." }\n        return file.absolutePath\n    }\n''')

write('app/src/main/java/com/tiagocrispo/furnitureshot/data/GenerationArtifactPolicy.kt', '''package com.tiagocrispo.furnitureshot.data\n\nimport java.io.File\n\n/** Pure policy for deleting only uncommitted ProductShot result artifacts. */\ninternal object GenerationArtifactPolicy {\n    fun isGeneratedResultFileName(name: String): Boolean =\n        name.startsWith("result_") && name.endsWith(".jpg") && name.length > "result_.jpg".length\n\n    fun selectUncommitted(\n        jobDirectory: String,\n        candidatePaths: List<String>,\n        protectedPaths: Set<String>,\n    ): Set<String> {\n        val job = runCatching { File(jobDirectory).canonicalFile }.getOrNull() ?: return emptySet()\n        val protected = protectedPaths.mapNotNull { runCatching { File(it).canonicalPath }.getOrNull() }.toSet()\n        return candidatePaths.mapNotNull { raw ->\n            val file = runCatching { File(raw).canonicalFile }.getOrNull() ?: return@mapNotNull null\n            val directChild = file.parentFile?.canonicalPath == job.canonicalPath\n            if (directChild && isGeneratedResultFileName(file.name) && file.canonicalPath !in protected) {\n                file.absolutePath\n            } else null\n        }.toSet()\n    }\n}\n''')

write('app/src/test/java/com/tiagocrispo/furnitureshot/data/GenerationArtifactPolicyTest.kt', '''package com.tiagocrispo.furnitureshot.data\n\nimport org.junit.Assert.assertEquals\nimport org.junit.Assert.assertFalse\nimport org.junit.Assert.assertTrue\nimport org.junit.Test\nimport java.io.File\nimport java.nio.file.Files\n\nclass GenerationArtifactPolicyTest {\n    @Test fun resultNameContractIsStrict() {\n        assertTrue(GenerationArtifactPolicy.isGeneratedResultFileName("result_123_abc.jpg"))\n        assertFalse(GenerationArtifactPolicy.isGeneratedResultFileName("original.jpg"))\n        assertFalse(GenerationArtifactPolicy.isGeneratedResultFileName("result_.jpg"))\n        assertFalse(GenerationArtifactPolicy.isGeneratedResultFileName("result_123.png"))\n    }\n\n    @Test fun orphanResultInSameJobIsSelected() = withJob { job ->\n        val orphan = File(job, "result_1_orphan.jpg").apply { writeText("x") }\n        assertEquals(setOf(orphan.canonicalPath), select(job, listOf(orphan), emptySet()))\n    }\n\n    @Test fun previousValidResultIsProtected() = withJob { job ->\n        val previous = File(job, "result_1_previous.jpg").apply { writeText("x") }\n        assertTrue(select(job, listOf(previous), setOf(previous.canonicalPath)).isEmpty())\n    }\n\n    @Test fun historyBackedResultIsProtectedWhileNewOrphanIsRemoved() = withJob { job ->\n        val history = File(job, "result_1_history.jpg").apply { writeText("x") }\n        val orphan = File(job, "result_2_orphan.jpg").apply { writeText("x") }\n        assertEquals(setOf(orphan.canonicalPath), select(job, listOf(history, orphan), setOf(history.canonicalPath)))\n    }\n\n    @Test fun foreignJobResultCanNeverBeDeleted() {\n        val a = Files.createTempDirectory("ps_a").toFile()\n        val b = Files.createTempDirectory("ps_b").toFile()\n        try {\n            val foreign = File(b, "result_1_foreign.jpg").apply { writeText("x") }\n            assertTrue(select(a, listOf(foreign), emptySet()).isEmpty())\n        } finally { a.deleteRecursively(); b.deleteRecursively() }\n    }\n\n    @Test fun originalsTempsAndNestedFilesAreIgnored() = withJob { job ->\n        val original = File(job, "original.jpg").apply { writeText("x") }\n        val temp = File(job, ".result_1.jpg.tmp").apply { writeText("x") }\n        val nestedDir = File(job, "nested").apply { mkdirs() }\n        val nested = File(nestedDir, "result_2_nested.jpg").apply { writeText("x") }\n        assertTrue(select(job, listOf(original, temp, nested), emptySet()).isEmpty())\n    }\n\n    private fun select(job: File, files: List<File>, protected: Set<String>) =\n        GenerationArtifactPolicy.selectUncommitted(job.canonicalPath, files.map { it.canonicalPath }, protected)\n\n    private inline fun withJob(block: (File) -> Unit) {\n        val job = Files.createTempDirectory("ps_job").toFile()\n        try { block(job) } finally { job.deleteRecursively() }\n    }\n}\n''')

rel = 'scripts/static_validate.py'
insert = "mask_test = text('app/src/test/java/com/tiagocrispo/furnitureshot/processing/SegmentationMaskQualityGateTest.kt')\n"
replace_exact(rel, insert, insert + "artifact_policy = text('app/src/main/java/com/tiagocrispo/furnitureshot/data/GenerationArtifactPolicy.kt')\nartifact_test = text('app/src/test/java/com/tiagocrispo/furnitureshot/data/GenerationArtifactPolicyTest.kt')\nbroker = text('app/src/main/java/com/tiagocrispo/furnitureshot/processing/BackgroundGenerationBroker.kt')\nprovider = text('app/src/main/java/com/tiagocrispo/furnitureshot/processing/MediaPipeReflectiveBackgroundProvider.kt')\nfinish = text('app/src/main/java/com/tiagocrispo/furnitureshot/processing/FinishPassEngine.kt')\n")
append_before = "print('PRODUCTSHOT_V1_0_0_FINAL_STATIC_VALIDATION_OK')\n"
checks = '''req('suspend fun tryGenerate' in generator and generator.count('coroutineContext.ensureActive()') >= 3, 'MediaPipe attempt loop is not cooperatively cancellable')\nreq('suspend fun tryAcquirePlate' in broker and 'delay(125)' in broker and 'Thread.sleep' not in broker, 'background broker still blocks cancellation')\nreq('suspend fun tryRender' in provider, 'provider does not propagate suspend cancellation')\nreq('transientBackgroundPath' in engine and 'deleteTransientCacheFile(context, transientBackgroundPath)' in engine, 'background artifact is not finally-owned')\nreq('onProgress(100, "Listo")' not in engine, 'cancellable callback remains after final persistence')\nreq('validateImageFile(temp, minimumBytes = 1_024L' in store and 'output.fd.sync()' in store, 'input import is not validated/atomic')\nreq('requireValidGeneratedResult' in store and ui.count('requireValidGeneratedResult') >= 2, 'pre-commit result validation missing')\nreq('deleteUncommittedGeneratedResults' in store and 'deleteUncommittedGeneratedResults(context, source, previousResult)' in ui, 'job-wide cancellation reconciliation missing')\nreq('GenerationArtifactPolicy.selectUncommitted' in store and 'directChild' in artifact_policy, 'safe orphan artifact policy missing')\nreq('foreignJobResultCanNeverBeDeleted' in artifact_test and 'historyBackedResultIsProtectedWhileNewOrphanIsRemoved' in artifact_test, 'artifact rollback tests missing')\nreq('require(file.isFile)' in finish, 'finish layer still accepts vanished output')\n'''
replace_exact(rel, append_before, checks + append_before)

print('PRODUCTSHOT_BLOCK20_PIPELINE_INTEGRATION_APPLIED')
