from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()

old = '''    private fun recoverLinearStructures(alpha: FloatArray, rgb: IntArray, bg: FloatArray, width: Int, height: Int) {
        val copy = alpha.clone()
        for (y in 2 until height - 2) {
            for (x in 2 until width - 2) {
'''
new = '''    private fun recoverLinearStructures(alpha: FloatArray, rgb: IntArray, bg: FloatArray, width: Int, height: Int) {
        val copy = alpha.clone()
        // This routine samples +/-3 pixels. Starting at 2 produced a deterministic
        // ArrayIndexOutOfBoundsException on the first eligible row/column.
        for (y in 3 until height - 3) {
            for (x in 3 until width - 3) {
'''
if text.count(old) != 1:
    raise SystemExit(f"recoverLinearStructures marker mismatch: {text.count(old)}")
text = text.replace(old, new, 1)

old = '''        return when (manager?.memoryClass ?: 256) {
            in 0..192 -> 3000
            in 193..256 -> 3600
            in 257..384 -> 4096
            in 385..512 -> 4352
            else -> 4608
        }
'''
new = '''        return when (manager?.memoryClass ?: 256) {
            // MAX quality must stay inside the real Android heap. The previous
            // v0.8.0 values created multiple full-frame IntArray/FloatArray clones
            // simultaneously and could cross the heap limit before the OOM retry.
            in 0..192 -> 2200
            in 193..256 -> 2600
            in 257..384 -> 3000
            in 385..512 -> 3400
            else -> 3840
        }
'''
if text.count(old) != 1:
    raise SystemExit(f"dimension marker mismatch: {text.count(old)}")
text = text.replace(old, new, 1)

old = '''        topologyLock(alpha, source.width, source.height)
        recoverLinearStructures(alpha, rgb, bg, source.width, source.height)
        suppressMulticolorBackgroundLeaks(alpha, rgb, source.width, source.height)
        recoverLinearStructures(alpha, rgb, bg, source.width, source.height)
        adaptiveFeather(alpha, source.width, source.height)
'''
new = '''        // Final experimental refiners must never make the whole photo fail.
        // OOM is propagated so the safe-memory retry still works; any other
        // refinement failure falls back to the already valid high-resolution matte.
        try {
            topologyLock(alpha, source.width, source.height)
            recoverLinearStructures(alpha, rgb, bg, source.width, source.height)
            suppressMulticolorBackgroundLeaks(alpha, rgb, source.width, source.height)
            recoverLinearStructures(alpha, rgb, bg, source.width, source.height)
        } catch (oom: OutOfMemoryError) {
            throw oom
        } catch (_: Throwable) {
            // Keep the refined alpha generated by the stable passes above.
        }
        adaptiveFeather(alpha, source.width, source.height)
'''
if text.count(old) != 1:
    raise SystemExit(f"fault containment marker mismatch: {text.count(old)}")
text = text.replace(old, new, 1)

path.write_text(text)
print('v0.8.1 hotfix applied', path)
