from pathlib import Path
root=Path(__file__).resolve().parents[1]
def text(p): return (root/p).read_text(encoding='utf-8')
def need(cond,msg):
    if not cond: raise SystemExit('FAIL: '+msg)
    print('PASS:',msg)
build=text('app/build.gradle.kts'); manifest=text('app/src/main/AndroidManifest.xml')
main=text('app/src/main/java/com/fer/wavault/MainActivity.java')
media=text('app/src/main/java/com/fer/wavault/MediaCrypto.java')
crypto=text('app/src/main/java/com/fer/wavault/CryptoManager.java')
legacy=text('app/src/main/java/com/fer/wavault/LegacyPlainMigration.java')
watch=text('app/src/main/java/com/fer/wavault/CaptureWatchdog.java')
storage=text('app/src/main/java/com/fer/wavault/StorageAnalyzer.java')
provider=text('app/src/main/java/com/fer/wavault/VaultShareProvider.java')
crash=text('app/src/main/java/com/fer/wavault/CrashRegistry.java')
partial=text('app/src/main/java/com/fer/wavault/CaptureProcessingEngine.java')
listener=text('app/src/main/java/com/fer/wavault/WhatsAppNotificationListener.java')
need('versionCode = 71' in build and 'versionName = "0.5.21"' in build,'version 0.5.21 / code 71')
need('super(c, "wa_vault.db", null, 13)' in text('app/src/main/java/com/fer/wavault/VaultDb.java'),'SQLite v13 preserved')
need('android:allowBackup="false"' in manifest,'Android OS automatic copy disabled')
need('MODE_NONE' not in media and 'MODE_SENSITIVE' not in media and 'shouldEncrypt(Context c,String type,String origin){return true;}' in media,'mandatory media encryption')
need('showEncryptionModeDialog' not in main and 'Sin cifrado de archivos' not in main,'encryption-disable UI removed')
need('PARTIAL_ENCRYPTION_FAILED' in partial and 'partial.delete()' in partial,'partial bytes fail closed on encryption failure')
need('PREFIX=new byte[]{80,76,65,73,78,58}' in legacy and 'migrateMessages' in legacy and 'display_name' in legacy and 'event_log' in legacy,'one-shot legacy clear-text migration')
need('PLAIN:' not in crypto and 'Base64' not in crypto,'general text decryptor has no old literal decoder')
need('15L*60L*1000L' in storage and '2L*60L*1000L' in main and '15L * 60L * 1000L' in provider,'short-lived share cache')
need('ACTIVE_MS=45_000L' in watch and 'IDLE_MS=5L*60_000L' in watch and 'quiet?IDLE_MS:ACTIVE_MS' in watch,'adaptive watchdog 45s / 5min')
need('now-wd<7*60_000L' in main,'UI watchdog freshness matches deep idle')
need('watchdog_recovery_at' in watch and 'watchdog_maintenance_at' in watch,'time-based recovery and maintenance cadence')
need('setDefaultUncaughtExceptionHandler' in crash and 'getMessage()' not in crash and 'printStackTrace' not in crash,'privacy-safe crash registry')
need('CrashRegistry.summary(this)' in main and 'CrashRegistry.hasUnacknowledged(app)' in main,'crash diagnostics integrated')
need('version=0.5.21' in main and 'crash_last_component' in main,'diagnostic export updated')
need('REASON_APP_CANCEL_ALL' in listener and 'isAppDrivenRemovalReason' in listener,'strict delete hardening retained')
for forbidden in ['findNearestUnlinkedMedia','findBestPendingManualMessage','reconcileRecentUnlinkedPendingMedia','promotePendingNear','nearestArm(']:
    need(forbidden not in text('app/src/main/java/com/fer/wavault/VaultDb.java')+listener,'no nearest-winner API: '+forbidden)
print('v0.5.21 regression PASS')
