from pathlib import Path
root=Path(__file__).resolve().parents[1]
def rd(p): return (root/p).read_text(encoding='utf-8')
def req(c,m):
    if not c: raise AssertionError(m)
gradle=rd('app/build.gradle.kts'); manifest=rd('app/src/main/AndroidManifest.xml'); db=rd('app/src/main/java/com/fer/wavault/VaultDb.java'); main=rd('app/src/main/java/com/fer/wavault/MainActivity.java'); gal=rd('app/src/main/java/com/fer/wavault/GalleryExporter.java'); meta=rd('app/src/main/java/com/fer/wavault/MetadataPrivacy.java'); listener=rd('app/src/main/java/com/fer/wavault/WhatsAppNotificationListener.java'); voice=rd('app/src/main/java/com/fer/wavault/DirectVoiceWatcher.java'); dl=rd('app/src/main/java/com/fer/wavault/DownloadsExporter.java'); thumb=rd('app/src/main/java/com/fer/wavault/MediaThumbnailLoader.java'); app=rd('app/src/main/java/com/fer/wavault/VaultApp.java'); integ=rd('app/src/main/java/com/fer/wavault/CaptureIntegritySelfTest.java')
req('versionCode = 75' in gradle and 'versionName = "0.5.25"' in gradle,'version')
req('super(c, "wa_vault.db", null, 13)' in db,'schema')
req('android:allowBackup="false"' in manifest,'android copy disabled')
req('SavedCallback' in gal and 'updateGalleryUriForPath' in main and 'deleteUri' in gal,'gallery uri tracking/rollback')
req('putString("direct_watcher_last_event", eventName(e) + " · audio")' in voice and 'VaultFileNames.stagingName("early_","audio")' in voice,'direct voice privacy')
req('msgfp_' not in listener and 'MetadataPrivacy.token(getApplicationContext(),"msgtok"' in listener and 'MetadataPrivacy.token(getApplicationContext(),"convsnap"' in listener,'listener hmac tokens')
req('messageFingerprint(' in db and 'MetadataPrivacy.token(appContext,"msgfp"' in db and 'migrateMessageFingerprintsToHmac' in db,'db fingerprint hmac')
req('src_"+sha256("orphan|' not in db and 'MetadataPrivacy.token(appContext,"src","orphan|' in db,'no source sha fallback')
req('MIGRATION_0525' in meta and 'MIGRATION_RUNNING' in meta and 'runFinalMigrationAsync' in meta and 'prepareV0525' in meta,'versioned privacy migration')
req('migrateSensitiveSourceMetadata();' not in listener and 'wa-vault-metadata-privacy' not in listener,'no reconnect migration')
req('MetadataPrivacy.prepareV0525(this)' in app and 'MetadataPrivacy.runFinalMigrationAsync(this)' in app,'migration starts at process start')
req('Build.VERSION.SDK_INT < Build.VERSION_CODES.Q' in dl and 'getExternalStoragePublicDirectory' in dl and 'FileOutputStream' in dl and 'Manifest.permission.WRITE_EXTERNAL_STORAGE' in main,'android 8/9 downloads')
req('MetadataPrivacy.token(app,"thumb"' in thumb and 'MessageDigest' not in thumb,'thumbnail hmac')
req('countLegacyMessageFingerprints' in integ and 'finalMigrationComplete' in integ,'self test')
req('version=0.5.25' in main,'diag version')
req('deleteMediaPermanentlyInternal' in db and 'physicalGone' in db and 'retryPendingPhysicalDeletes' in db,'physical delete hardening retained')
for bad in ['findNearestUnlinkedMedia','findBestPendingManualMessage','promotePendingNear','nearestArm(']: req(bad not in db+main,'forbidden nearest guess '+bad)
req('REASON_APP_CANCEL' in listener and 'DELETE_UNVERIFIABLE' in listener and 'structuredPluralDeleteCount' in listener,'strict delete retained')
print('v0.5.25 regression PASS')
