from pathlib import Path
p=Path('A53Performance/app/src/main/java/com/fer/a53performance/MainActivity.java')
s=p.read_text()

def rep(old,new):
    global s
    if old not in s:
        raise SystemExit('missing pattern: '+old[:120])
    s=s.replace(old,new,1)

rep('import java.util.HashSet;\nimport java.util.List;', 'import java.util.HashSet;\nimport java.util.HashMap;\nimport java.util.List;')
rep('private Spinner filterSpinner,sortSpinner;', 'private Spinner filterSpinner,sortSpinner,volumeSpinner;')
rep('private Button loadMore,trashSelected,deleteSelected,scanButton,safeDuplicates,reviewSimilar;', 'private Button loadMore,trashSelected,deleteSelected,scanButton,safeDuplicates,reviewDuplicates,reviewSimilar;')
rep('private final ArrayList<StorageItem> pendingTrash=new ArrayList<>();', 'private final ArrayList<StorageItem> pendingTrash=new ArrayList<>();\n    private final HashMap<String,String> duplicateKeeperOverrides=new HashMap<>();')
rep('filterSpinner=null;sortSpinner=null;loadMore=null;', 'filterSpinner=null;sortSpinner=null;volumeSpinner=null;loadMore=null;')
rep('scanButton=null;safeDuplicates=null;reviewSimilar=null;', 'scanButton=null;safeDuplicates=null;reviewDuplicates=null;reviewSimilar=null;')
rep('box.addView(metricCard("Almacenamiento libre",FileAdapter.formatBytes(StorageRepository.freeBytes()),"Lectura en vivo del espacio físico disponible."));', 'box.addView(metricCard("Almacenamiento",storage.spaceSummary(),"Interno y microSD se miden por separado cuando están disponibles."));')
rep('LinearLayout top=card();storageSummary=text("Libre: "+FileAdapter.formatBytes(StorageRepository.freeBytes()),14,Color.WHITE,true);top.addView(storageSummary);', 'LinearLayout top=card();storageSummary=text(storage.spaceSummary(),14,Color.WHITE,true);top.addView(storageSummary);')
rep('filterSpinner.setSelection(Math.min(6,prefs.getInt("clean_filter",0)));sortSpinner.setSelection(Math.min(3,prefs.getInt("clean_sort",0)));', 'filterSpinner.setSelection(Math.min(6,prefs.getInt("clean_filter",0)));sortSpinner.setSelection(Math.min(3,prefs.getInt("clean_sort",0)));\n        volumeSpinner=spinner(new String[]{"Todos los almacenamientos","Interno","microSD"});volumeSpinner.setSelection(Math.min(2,prefs.getInt("clean_volume",0)));box.addView(volumeSpinner,new LinearLayout.LayoutParams(-1,dp(46)));')
rep('safeDuplicates=button("Seleccionar copias seguras");safeDuplicates.setVisibility(View.GONE);safeDuplicates.setOnClickListener(v->selectSafeDuplicates());box.addView(safeDuplicates,new LinearLayout.LayoutParams(-1,dp(46)));\n        reviewSimilar=button("Revisar grupos similares");', 'safeDuplicates=button("Seleccionar copias seguras");safeDuplicates.setVisibility(View.GONE);safeDuplicates.setOnClickListener(v->selectSafeDuplicates());box.addView(safeDuplicates,new LinearLayout.LayoutParams(-1,dp(46)));\n        reviewDuplicates=button("Revisar duplicados y copia a conservar");reviewDuplicates.setVisibility(View.GONE);reviewDuplicates.setOnClickListener(v->showDuplicateGroups());box.addView(reviewDuplicates,new LinearLayout.LayoutParams(-1,dp(46)));\n        reviewSimilar=button("Revisar grupos similares");')
rep('sortSpinner.setOnItemSelectedListener(simpleSelection(()->{if(sortSpinner==null)return;prefs.edit().putInt("clean_sort",sortSpinner.getSelectedItemPosition()).apply();applyFilter(true);}));', 'sortSpinner.setOnItemSelectedListener(simpleSelection(()->{if(sortSpinner==null)return;prefs.edit().putInt("clean_sort",sortSpinner.getSelectedItemPosition()).apply();applyFilter(true);}));\n        volumeSpinner.setOnItemSelectedListener(simpleSelection(()->{if(volumeSpinner==null)return;prefs.edit().putInt("clean_volume",volumeSpinner.getSelectedItemPosition()).apply();if(fileAdapter!=null)fileAdapter.clearSelection();visibleLimit=PAGE_SIZE;applyFilter(false);}));')
rep('if(scanRunning){storage.cancelScan();scanRunning=false;}analyzer.cancel();analysisRunning=false;duplicateReady=false;', 'if(scanRunning){storage.cancelScan();scanRunning=false;}analyzer.cancel();analysisRunning=false;duplicateKeeperOverrides.clear();duplicateReady=false;')
rep('if(safeDuplicates!=null)safeDuplicates.setVisibility(pos==5&&duplicateReady?View.VISIBLE:View.GONE);\n        if(reviewSimilar!=null)', 'if(safeDuplicates!=null)safeDuplicates.setVisibility(pos==5&&duplicateReady?View.VISIBLE:View.GONE);\n        if(reviewDuplicates!=null)reviewDuplicates.setVisibility(pos==5&&duplicateReady?View.VISIBLE:View.GONE);\n        if(reviewSimilar!=null)')
rep('analyzer.cancel();analysisRunning=false;duplicateReady=false;', 'analyzer.cancel();analysisRunning=false;duplicateKeeperOverrides.clear();duplicateReady=false;')
rep('filtered.clear();filtered.addAll(CleanerController.filterAndSort(storage.snapshot(),q,f,sort,duplicateKeys,similarKeys));', 'filtered.clear();filtered.addAll(CleanerController.filterAndSort(storage.snapshot(),q,f,sort,duplicateKeys,similarKeys));int vm=volumeSpinner==null?0:volumeSpinner.getSelectedItemPosition();filtered.removeIf(x->!StorageRepository.matchesVolume(x,vm));')
rep('private void updateCleanerSummary(){if(fileAdapter==null)return;if(storageSummary!=null)storageSummary.setText("Libre: "+FileAdapter.formatBytes(StorageRepository.freeBytes())+"  ·  "+fileAdapter.displayedCount()+"/"+filtered.size()+" visibles");', 'private void updateCleanerSummary(){if(fileAdapter==null)return;if(storageSummary!=null)storageSummary.setText(storage.spaceSummary()+"\\n"+fileAdapter.displayedCount()+"/"+filtered.size()+" visibles");')
rep('if(duplicateMode)message+="\\n\\nProtección de duplicados activa: se conservará al menos una copia exacta de cada grupo.";', 'if(duplicateMode)message+="\\n\\nProtección de duplicados activa: se conservará la copia marcada en cada grupo. Podés cambiarla desde Revisar duplicados.";')
rep('if(all&&chosen.remove(group.keeperKey))changed=true;', 'String keep=effectiveKeeper(group);if(all&&chosen.remove(keep))changed=true;')
rep('if(fileAdapter==null||duplicateResult==null)return;ArrayList<StorageItem> safe=new ArrayList<>();for(StorageItem x:storage.snapshot())if(duplicateResult.safeDeleteKeys.contains(x.stableKey()))safe.add(x);fileAdapter.setSelection(safe);', 'if(fileAdapter==null||duplicateResult==null)return;ArrayList<StorageItem> safe=new ArrayList<>();for(StorageAnalyzer.DuplicateGroup group:duplicateResult.groupList){String keep=effectiveKeeper(group);for(StorageItem x:group.items)if(!x.stableKey().equals(keep))safe.add(x);}fileAdapter.setSelection(safe);')
rep('if(duplicateResult==null)return;if(safeDuplicates!=null)safeDuplicates.setVisibility(filterSpinner!=null&&filterSpinner.getSelectedItemPosition()==5?View.VISIBLE:View.GONE);if(scanStatus!=null)', 'if(duplicateResult==null)return;if(safeDuplicates!=null)safeDuplicates.setVisibility(filterSpinner!=null&&filterSpinner.getSelectedItemPosition()==5?View.VISIBLE:View.GONE);if(reviewDuplicates!=null)reviewDuplicates.setVisibility(filterSpinner!=null&&filterSpinner.getSelectedItemPosition()==5?View.VISIBLE:View.GONE);if(scanStatus!=null)')
rep('LinearLayout about=card();about.addView(text("v1.15.9 STORAGE / SAFE RAM",16,ACCENT,true));about.addView(text("Multi-volumen/microSD, índice incremental, perfiles deterministas, RAM sensible y revisión por grupos de fotos similares.",13,MUTED,false));box.addView(about);', 'LinearLayout about=card();about.addView(text("v1.15.10 DEVICE HARDENING",16,ACCENT,true));about.addView(text("RAM fail-safe, Shizuku con detección de caída, almacenamiento Interno/microSD visible y duplicados con copia a conservar elegible.",13,MUTED,false));box.addView(about);')
anchor='    private void updateSimilarUi(){'
if anchor not in s: raise SystemExit('missing method anchor')
extra='''    private String effectiveKeeper(StorageAnalyzer.DuplicateGroup group){String override=duplicateKeeperOverrides.get(group.keeperKey);if(override!=null)for(StorageItem x:group.items)if(x.stableKey().equals(override))return override;return group.keeperKey;}\n\n    private StorageItem keeperItem(StorageAnalyzer.DuplicateGroup group){String key=effectiveKeeper(group);for(StorageItem x:group.items)if(x.stableKey().equals(key))return x;return group.items.get(0);}\n\n    private void showDuplicateGroups(){\n        if(duplicateResult==null||duplicateResult.groupList.isEmpty()){toast("No hay duplicados para revisar.");return;}\n        int n=Math.min(100,duplicateResult.groupList.size());String[] labels=new String[n];\n        for(int i=0;i<n;i++){StorageAnalyzer.DuplicateGroup g=duplicateResult.groupList.get(i);StorageItem keep=keeperItem(g);labels[i]="Grupo "+(i+1)+" · "+g.items.size()+" copias · liberar "+FileAdapter.formatBytes(g.recoverableBytes)+"\\nSe conservará: "+keep.name+" · "+StorageRepository.volumeLabel(keep);}\n        new AlertDialog.Builder(this).setTitle("Duplicados exactos").setItems(labels,(d,which)->showDuplicateKeeperChooser(duplicateResult.groupList.get(which),which)).setNegativeButton("Cerrar",null).show();\n    }\n\n    private void showDuplicateKeeperChooser(StorageAnalyzer.DuplicateGroup group,int groupIndex){\n        String current=effectiveKeeper(group);String[] choices=new String[group.items.size()];int selected=0;\n        for(int i=0;i<group.items.size();i++){StorageItem x=group.items.get(i);if(x.stableKey().equals(current))selected=i;String path=x.path==null||x.path.isBlank()?"ruta MediaStore":x.path;choices[i]=x.name+"\\n"+StorageRepository.volumeLabel(x)+" · "+FileAdapter.formatBytes(x.size)+" · "+path;}\n        final int[] pick={selected};new AlertDialog.Builder(this).setTitle("Se conservará esta copia").setSingleChoiceItems(choices,selected,(dialog,which)->pick[0]=which).setNegativeButton("Cancelar",null).setPositiveButton("Conservar esta",(dialog,w)->{StorageItem chosen=group.items.get(pick[0]);duplicateKeeperOverrides.put(group.keeperKey,chosen.stableKey());if(fileAdapter!=null)fileAdapter.clearSelection();if(scanStatus!=null)scanStatus.setText("Grupo "+(groupIndex+1)+": se conservará "+chosen.name+" · "+StorageRepository.volumeLabel(chosen));updateDuplicateUi();}).show();\n    }\n\n'''
s=s.replace(anchor,extra+anchor,1)
p.write_text(s)
print('patched MainActivity for v1.15.10')
