from pathlib import Path

p=Path('A53Performance/app/src/main/java/com/fer/a53performance/MainActivity.java')
s=p.read_text()

old='''        LinearLayout files=card();files.addView(text("Acceso a archivos",16,Color.WHITE,true));files.addView(text(Environment.isExternalStorageManager()?"Acceso completo activo":"Necesario para gestionar archivos fuera de las colecciones estándar",13,MUTED,false));Button all=button(Environment.isExternalStorageManager()?"Acceso activo":"Conceder acceso");all.setOnClickListener(v->openAllFilesSettings());files.addView(all);box.addView(files);\n        LinearLayout protectedCard=card();'''
new='''        LinearLayout files=card();files.addView(text("Acceso a archivos",16,Color.WHITE,true));files.addView(text(Environment.isExternalStorageManager()?"Acceso completo activo":"Necesario para gestionar archivos fuera de las colecciones estándar",13,MUTED,false));Button all=button(Environment.isExternalStorageManager()?"Acceso activo":"Conceder acceso");all.setOnClickListener(v->openAllFilesSettings());files.addView(all);box.addView(files);\n        LinearLayout diagnostics=card();diagnostics.addView(text("Diagnóstico de permisos",16,Color.WHITE,true));TextView diagnosticText=text(permissionStatus(),13,MUTED,false);diagnostics.addView(diagnosticText);Button repair=button("Reparar permisos faltantes");repair.setOnClickListener(v->{prefs.edit().putBoolean("permission_flow_v1154",false).apply();startPermissionFlow();diagnosticText.setText(permissionStatus());});diagnostics.addView(repair);box.addView(diagnostics);\n        LinearLayout protectedCard=card();'''
assert old in s
s=s.replace(old,new,1)

s=s.replace('''        LinearLayout about=card();about.addView(text("v1.15.5 STABILITY CORE",16,ACCENT,true));about.addView(text("Shizuku UserService, Auto persistente opcional, análisis bajo demanda con caché, agrupación de similares más estricta y pruebas de arranque Android.",13,MUTED,false));box.addView(about);''','''        LinearLayout about=card();about.addView(text("v1.15.6 HARDENED",16,ACCENT,true));about.addView(text("Shizuku con operaciones cerradas, menos mantenimiento, duplicados con prefiltro rápido, similitud indexada, IDs 64-bit y diagnóstico reparable de permisos.",13,MUTED,false));box.addView(about);''',1)

old='''        ArrayList<String> need=new ArrayList<>();if(Build.VERSION.SDK_INT>=33){if(checkSelfPermission(Manifest.permission.READ_MEDIA_IMAGES)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.READ_MEDIA_IMAGES);if(checkSelfPermission(Manifest.permission.READ_MEDIA_VIDEO)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.READ_MEDIA_VIDEO);if(checkSelfPermission(Manifest.permission.READ_MEDIA_AUDIO)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.READ_MEDIA_AUDIO);if(checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.POST_NOTIFICATIONS);}else if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.READ_EXTERNAL_STORAGE);'''
new='''        ArrayList<String> need=new ArrayList<>();if(Build.VERSION.SDK_INT>=33){if(checkSelfPermission(Manifest.permission.READ_MEDIA_IMAGES)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.READ_MEDIA_IMAGES);if(checkSelfPermission(Manifest.permission.READ_MEDIA_VIDEO)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.READ_MEDIA_VIDEO);if(checkSelfPermission(Manifest.permission.READ_MEDIA_AUDIO)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.READ_MEDIA_AUDIO);}else if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.READ_EXTERNAL_STORAGE);'''
assert old in s
s=s.replace(old,new,1)

marker='''    private void openAllFilesSettings(){try{Intent i=new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,Uri.parse("package:"+getPackageName()));startActivity(i);}catch(Throwable e){startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));}}\n\n    private void saveListAnchor()'''
replacement='''    private void openAllFilesSettings(){try{Intent i=new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,Uri.parse("package:"+getPackageName()));startActivity(i);}catch(Throwable e){startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));}}\n\n    private String permissionStatus(){\n        ArrayList<String> missing=new ArrayList<>();\n        if(Build.VERSION.SDK_INT>=33){\n            if(checkSelfPermission(Manifest.permission.READ_MEDIA_IMAGES)!=PackageManager.PERMISSION_GRANTED)missing.add("imágenes");\n            if(checkSelfPermission(Manifest.permission.READ_MEDIA_VIDEO)!=PackageManager.PERMISSION_GRANTED)missing.add("videos");\n            if(checkSelfPermission(Manifest.permission.READ_MEDIA_AUDIO)!=PackageManager.PERMISSION_GRANTED)missing.add("audio");\n        }else if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)missing.add("archivos");\n        if(Build.VERSION.SDK_INT>=30&&!Environment.isExternalStorageManager())missing.add("acceso completo a archivos");\n        if(!shell.available())missing.add("Shizuku activo");else if(!shell.permissionGranted())missing.add("permiso Shizuku");\n        return missing.isEmpty()?"Todo listo.":"Falta: "+String.join(" · ",missing)+".";\n    }\n\n    private void saveListAnchor()'''
assert marker in s
s=s.replace(marker,replacement,1)

p.write_text(s)
